version: 2
jobs:
  test:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          command: |
            make e2e
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
