name: e2e tests

on:
  push:
    paths:
      - 'backend/**'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: make e2e test
        working-directory: backend
        run: make e2e
